[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run deploy"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
